// Generated by generate.mjs - do not edit by hand. Run `node src/core/runtime/stub/generate.mjs` to regenerate.
/** The compiled stub-doom.wasm module, base64-encoded so RuntimeRegistry can write it into the
 * VirtualFileSystem synchronously at install time without a network fetch. */
export const STUB_DOOM_WASM_BASE64 = 'AGFzbQEAAAABDwNgAX8AYAN/f38AYAABfwIRAQNlbnYJZ2V0X2lucHV0AAIDAwIAAQUDAQABBgYBfwFBAAsHHAMGbWVtb3J5AgAGdXBkYXRlAAEGcmVuZGVyAAIKewIOACMAIABqQcCEPXAkAAtqAQN/IAEgAmwhA0EAIQQCQANAIAQgA08NASAAIARBBGxqIQUgBSAEIwBqQf8BcToAACAFIARBA2wjAEECbGpB/wFxOgABIAUjAEEFbCAEa0H/AXE6AAIgBUH/AToAAyAEQQFqIQQMAAsLCw==';

export function decodeStubDoomWasm(): Uint8Array {
  const binary = atob(STUB_DOOM_WASM_BASE64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}
